# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("create_stan_model works", {
  expect_equal(as.character(summary(create_stan_model('weights ~ 1', data.frame(weights= c(2,1,0,4,2,2,2,1,1,3,8)),"normal"))[2]), "stanmodel")
})

devtools::load_all("/Users/chloevillette/Desktop/my.mbm.package")

test_that("fit_stan_model works", {
  # Define normal_model_base within the test
  normal_model_base <- my.mbm.package::create_stan_model('weights ~ 1', data.frame(weights=c(2,1,0,4,2,2,2,1,1,3,8)), "normal")
  
  expect_equal(as.character(summary(fit_stan_model(normal_model_base,'weights ~ 1', data.frame(weights=c(2,1,0,4,2,2,2,1,1,3,8) ), family="normal"))$formula[1]), "weights ~ 1")
})
