# WARNING - Generated by {fusen} from dev/flat_mbm_function.Rmd: do not edit by hand

test_that("create_stan_model works", {
  expect_equal(as.character(summary(create_stan_model('weights ~ 1', data.frame(weights= c(2,1,0,4,2,2,2,1,1,3,8)),"normal"))[2]), "stanmodel")
})

devtools::load_all("/Users/chloevillette/Desktop/strongTies")



test_that("fit_stan_model works", {
  # Define normal_model_base within the test
  normal_model_base <- create_stan_model('weights ~ 1', data.frame(weights=c(2,1,0,4,2,2,2,1,1,3,8)), "normal")
  
  expect_equal(as.character(summary(fit_stan_model(normal_model_base,'weights ~ 1', data.frame(weights=c(2,1,0,4,2,2,2,1,1,3,8) ), family="normal"))$formula[1]), "weights ~ 1")
})

context("Test that the MBM function works correctly")

### POSITIVE TEST
# First, simulate a normal distribution of weights, so no strong ties !
weights = round(abs(rnorm(30,2,1))) 
# Then add an extra weight as a strong tie
weights[length(weights)+1] <- 10

strong.ties <- model_based_extraction(weights, sd_diff = 0, min_diff=3, model_backend="rstan")

test_that("The MBM function identifies and classifies strong ties correctly", {
 expect_equal(sum(strong.ties$strong)==1, TRUE)
})

### NEGATIVE TEST
# simulate a normal distribution of weights, so no strong ties !
weights = round(abs(rnorm(30,2,1)))

strong.ties.f <- model_based_extraction(weights, sd_diff = 0, min_diff=3, model_backend="rstan")

test_that("The MBM function doesn't identify and classify any strong ties from the normally weight distribution", {
  expect_equal(sum(strong.ties.f$strong)==1, FALSE)

})
